amovie_async@InRing0,volume=precision=fixed, volume@VolRing0=precision=fixed[a0],
amovie_async@InMusic0=indexmem=32768:fadein=500,afade,volume=precision=fixed,volume@VolMedia0=precision=fixed[a1],
amovie_async@InMusic1=indexmem=32768:fadein=500,afade,volume=precision=fixed,volume@VolMedia3=precision=fixed[a5],
amovie_async@InMedia0=indexmem=32768,volume=precision=fixed,volume@VolMedia1=precision=fixed[a2],
amovie_async@InAlarm0,afade,volume=precision=fixed,volume@VolAlarm0=precision=fixed[a3],
amovie_async@InEnforced0,afade,volume=precision=fixed[a4],
[a0][a1][a2][a3][a4][a5]amix=inputs=6:timeout=40:first_input=-1:normalize=0[mix],
adevsrc@SCOrx=format=nuttx:devname=/dev/audio/pcm1c,afade=d=0.5,volume@VolSCO=precision=fixed[pcm1c],
[mix][pcm1c]astreamselect@SelPlay=inputs=2:map=-1 -1[pcm0p][a2dp],
[pcm0p]adevsink@pcm0p=format=nuttx:devname=/dev/audio/pcm0p,
[a2dp]adevsink@a2dp=format=bluelet:devname=default:server_name=sensor;
adevsrc@pcm0c=format=nuttx:devname=/dev/audio/pcm0c[pcm0c],
[pcm0c]astreamselect@SelCap=inputs=1:map=0 -1[capture][pcm1p],
[capture]amoviesink_async@cap,
[pcm1p]adevsink@SCOtx=format=nuttx:devname=/dev/audio/pcm1p
