amovie_async@InRing0,volume=precision=fixed, volume@VolRing0=precision=fixed[a0],
amovie_async@InRing1,volume=precision=fixed,volume@VolRing1=precision=fixed[a1],
amovie_async@InMusic0,afade,volume=precision=fixed,volume@VolMusic0=precision=fixed[a2],
amovie_async@InMusic1,afade,volume=precision=fixed,volume@VolMusic1=precision=fixed[a3],
amovie_async@InMusic2,afade,volume=precision=fixed,volume@VolMusic2=precision=fixed[a4],
amovie_async@InMusic3,afade,volume=precision=fixed,volume@VolMusic3=precision=fixed[a5],
amovie_async@InAlarm0,volume=precision=fixed,volume@VolAlarm0=precision=fixed[a6],
[a0][a1][a2][a3][a4][a5][a6]amix=inputs=7:timeout=40:first_input=-1:dropout_transition=0.5[mix],
[mix]adevsink@pcm0p=format=nuttx:devname=/dev/audio/pcm0p;
adevsrc@pcm0c=format=nuttx:devname=/dev/audio/pcm0c[pcm0c],
[pcm0c]astreamselect@SelCap=inputs=1:map=0 0[capture0][capture1],
[capture0]amoviesink_async@Capture0,
[capture1]amoviesink_async@Capture1
