#board_cfg.mk
#configs will shared with every core or subsys

CONFIG_A7_BIN_OFFSET := 0x600000
CONFIG_A7_SRAM_SIZE := 0x80000
CONFIG_DSP_IMAGE_COMP := y
CONFIG_DSP_USE_PSRAM := n

#SRAM mem layout
RAM_S_SIZE := 0
RAMCPX_SIZE := 0
RAMCP_SIZE := 0
RAMCP_SUBSYS_SIZE := 0
BT_RAMRUN_SIZE := 0
RAM_RSV_SIZE := $(CONFIG_A7_SRAM_SIZE)

#PSRAM mem layout
PSRAMDSP_SIZE := 0
PSRAMCP_SIZE := 0

#PSRAMUHS mem layout
MCU_PSRAMUHS_SIZE := 0

#SHARED mem layout
CONFIG_RPTUNMEM_ON_PSRAMUHS := y
CONFIG_PSRAMUHS_TOTAL_SIZE := 0x2000000
CONFIG_BES_UNCACHE_HEAP_SIZE := 0x100000
CONFIG_BES_RPTUN_HEAP_SIZE := 0x20000
ifeq ($(CONFIG_RPTUNMEM_ON_PSRAMUHS),y)
CONFIG_BES_UNCACHE_HEAP_BASE := 0x38000000+$(CONFIG_PSRAMUHS_TOTAL_SIZE)-$(MCU_PSRAMUHS_SIZE)-$(CONFIG_BES_UNCACHE_HEAP_SIZE)
PSRAMUHS_NC_SIZE := $(CONFIG_BES_UNCACHE_HEAP_SIZE)
SRAM_NC_SIZE := 0
else
CONFIG_BES_UNCACHE_HEAP_BASE := 0x50000000+$(CONFIG_A7_SRAM_SIZE)-$(CONFIG_BES_UNCACHE_HEAP_SIZE)
SRAM_NC_SIZE := $(CONFIG_BES_UNCACHE_HEAP_SIZE)
PSRAMUHS_NC_SIZE := 0
endif

#GPIO layout
A7_GPIO_IRQ_MAP := 0x800000

#cflags for nuttx code
CFLAGS += -DCONFIG_A7_BIN_OFFSET=$(CONFIG_A7_BIN_OFFSET) -DCONFIG_A7_SRAM_SIZE=$(CONFIG_A7_SRAM_SIZE)-$(SRAM_NC_SIZE)
CFLAGS += -DCONFIG_MCU_PSRAMUHS_SIZE=$(MCU_PSRAMUHS_SIZE)
CFLAGS += -DCONFIG_BES_UNCACHE_HEAP_BASE=$(CONFIG_BES_UNCACHE_HEAP_BASE)
CFLAGS += -DCONFIG_BES_UNCACHE_HEAP_SIZE=$(CONFIG_BES_UNCACHE_HEAP_SIZE)
CFLAGS += -DCONFIG_BES_RPTUN_HEAP_SIZE=$(CONFIG_BES_RPTUN_HEAP_SIZE)
ifeq ($(CONFIG_DSP_IMAGE_COMP),y)
CFLAGS += -DCONFIG_DSP_IMAGE_COMP
endif
ifeq ($(CONFIG_DSP_USE_PSRAM),y)
CFLAGS += -DCONFIG_DSP_USE_PSRAM
endif
